version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DOCKER=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=quaiqi
      - DB_USER=quaiqi
      - DB_PASSWORD=quaiqi_password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./quai_price_history.csv:/app/quai_price_history.csv
    networks:
      - quaiqi-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=quaiqi
      - POSTGRES_USER=quaiqi
      - POSTGRES_PASSWORD=quaiqi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quaiqi-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quaiqi -d quaiqi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  quaiqi-network:
    driver: bridge 