apiVersion: apps/v1
kind: Deployment
metadata:
  name: quaiqi-db
  labels:
    app: quaiqi-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quaiqi-db
  template:
    metadata:
      labels:
        app: quaiqi-db
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: quaiqi-db
        image: quainetwork/quaiqi-db:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        env:
        - name: POSTGRES_DB
          value: "quaiqi"
        - name: POSTGRES_USER
          value: "quaiqi"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quaiqi-db-secret
              key: password
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: quaiqi-db-pvc 